Tag: SL_pNN
Basepath: /home/gsaha/Work/Delphes_Analyses/Project_ColorOctet/ColOctet_v2_JobOutput_taultauh/results
Lumi: 3000000
Mass: [66, 75, 88, 100, 121, 147]

Infiles:
  Signal :
    M_66  : [Sig_Mh3_66p39_MSSR_876p9_MSSI_800_taultauh_BDTD_mvaIn.root,  0.05, 'signal_mA_66.39']
    M_75  : [Sig_Mh3_75p07_MSSR_885p2_MSSI_800_taultauh_BDTD_mvaIn.root,  0.05, 'signal_mA_75.07']
    M_88  : [Sig_Mh3_80p09_MSSR_882p6_MSSI_800_taultauh_BDTD_mvaIn.root,  0.05, 'signal_mA_88.09']
    M_100 : [Sig_Mh3_100p31_MSSR_909p7_MSSI_800_taultauh_BDTD_mvaIn.root, 0.05, 'signal_mA_100.3']
    M_121 : [Sig_Mh3_121p11_MSSR_938_MSSI_800_taultauh_BDTD_mvaIn.root,   0.05, 'signal_mA_121.1']
    M_147 : [Sig_Mh3_147_MSSR_950p3_MSSI_800_taultauh_BDTD_mvaIn.root,    0.05, 'signal_mA_147.0']
  Background :
    TTJets2L    : [Bkg_TTJets_DiLep_Set_New_taultauh_BDTD_mvaIn.root, 107.65,  'T(T) + Jets']
    TTJets1L    : [Bkg_TTJets_SingleLep_taultauh_BDTD_mvaIn.root,     437.14,  'T(T) + Jets']
    TTWJetsLNu  : [Bkg_TTWJetsToLNu_taultauh_BDTD_mvaIn.root,           0.25,   'TTV + Jets']
    TTWToQQ     : [Bkg_TTWToQQ_taultauh_BDTD_mvaIn.root,               0.103,   'TTV + Jets']
    TTZJetsLL   : [Bkg_TTZJetsToLL_taultauh_BDTD_mvaIn.root,            0.24,   'TTV + Jets']
    TTZToQQ     : [Bkg_TTZnojetsToQQ_taultauh_BDTD_mvaIn.root,         0.206,   'TTV + Jets']
    TTH         : [Bkg_TTHnojetsToTauTau_taultauh_BDTD_mvaIn.root,     0.006,   'TTV + Jets']
    WZTo3LNu    : [Bkg_WZTo3LNu_012Jets_taultauh_BDTD_mvaIn.root,      2.273, 'VV(V) + Jets']
    WZTo2L2Q    : [Bkg_WZTo2L2Q_012Jets_taultauh_BDTD_mvaIn.root,      4.504, 'VV(V) + Jets']
    ZZTo4L      : [Bkg_ZZTo4L_012Jets_taultauh_BDTD_mvaIn.root,        0.187, 'VV(V) + Jets']
    ZZTo2b2tau  : [Bkg_ZZ_taultauh_BDTD_mvaIn.root,                   0.2086,     'bbtautau']
    ZhTo2b2tau  : [Bkg_Zh_taultauh_BDTD_mvaIn.root,                    0.022,     'bbtautau']
    bbtata      : [Bkg_bbtautau_taultauh_BDTD_mvaIn.root,              0.114,     'bbtautau']
    TW2L        : [Bkg_tWTo2L2Nu_taultauh_BDTD_mvaIn.root,             47.78,  'T(T) + Jets']
    WWW         : [Bkg_WWW_taultauh_BDTD_mvaIn.root,                   0.236, 'VV(V) + Jets']
    WWZ         : [Bkg_WWZ_taultauh_BDTD_mvaIn.root,                   0.189, 'VV(V) + Jets']
    WZZ         : [Bkg_WZZ_taultauh_BDTD_mvaIn.root,                   0.064, 'VV(V) + Jets']
    ZZZ         : [Bkg_ZZZ_taultauh_BDTD_mvaIn.root,                   0.016, 'VV(V) + Jets']

Intree: EventsSL

Features:
  Variables:
    pt_bjet1                  : [100, 0.0, 800.0]
    pt_bjet2                  : [50, 0.0, 400.0]
    eta_bjet1                 : [25, 0.0, 5]
    eta_bjet2                 : [25, 0.0, 5]
    met                       : [50, 0.0, 200.0]
    pt_tauh                   : [50, 0.0, 200.0]
    eta_tauh                  : [25, 0.0, 5]
    pt_lep                    : [50, 0.0, 200.0]
    eta_lep                   : [25, 0.0, 5] 
    dr_lep_tauh               : [25, 0.0, 5]
    dphi_lep_met              : [32, 0.0, 3.2]
    dphi_tauh_met             : [32, 0.0, 3.2]
    pt_h3                     : [50, 0.0, 400.0]
    dr_lep_h3                 : [25, 0.0, 5]
    dr_tauh_h3                : [25, 0.0, 5]
    dr_lep_tauh_x_pt_h3       : [60, 0.0, 600.0]
    dr_bjet1_bjet2            : [25, 0.0, 5]
    pt_ss2                    : [60, 0.0, 600.0]
    dr_bjet1_ss2              : [25, 0.0, 5]
    dr_bjet2_ss2              : [25, 0.0, 5]
    dr_bjet1_bjet2_x_pt_ss2   : [100, 0, 1500]
    dr_lep_bjet1              : [25, 0.0, 5]
    dr_lep_bjet2              : [25, 0.0, 5]
    dr_tauh_bjet1             : [25, 0.0, 5]
    dr_tauh_bjet2             : [25, 0.0, 5]
    dphi_bjet1_met            : [32, 0.0, 3.2]
    dphi_bjet2_met            : [32, 0.0, 3.2]
    dr_bjet1_h3               : [25, 0.0, 5]
    dr_bjet2_h3               : [25, 0.0, 5]
    dr_lep_ss2                : [25, 0.0, 5]
    dr_tauh_ss2               : [25, 0.0, 5]
    costhetaS_h3lep           : [20, 0.0, 1.0]     
    costhetaS_ss2b            : [20, 0.0, 1.0]
    dr_min_alljets            : [25, 0.0, 5.0]
    dr_max_alljets            : [30, 0.0, 10.0]
    smin                      : [300, 0.0, 1500.0]
    njets                     : [15, 0.0, 15.0]
    nbjets                    : [5, 0.0, 5.0]
    nljets                    : [10, 0.0, 10.0]
  Spectators:
    invm_h3                   : [100, 0.0, 400.0]
    invm_h3_vis               : [100, 0.0, 400.0]
    invm_ss2                  : [200, 0.0, 1000.0]
    invm_ss1_vis              : [200, 0.0, 1200.0]
    invm_ss1                  : [200, 0.0, 1200.0]


DoScaling : yes
UseNormForPlots : yes
DoTrain : no

# For binary classification
# Final activation : softmax
ModelParams:
  Layers:     [512, 256, 128, 54, 8]
  BatchNorms: [True, True, True, True, True]
  Dropout:    [0.2,  0.2,  0.2,  0.2,  0.2]
  L2:         [0.01, 0.01, 0.01, 0.01, 0.01] #0.001
  activ:      ['relu','relu','relu','relu','relu']

TrainingParams:
  Loss: 'binary_crossentropy'
  LR: 0.001
  Metrics: ['accuracy','auc','precision','recall']
  trainTestSplit: 0.80
  valSplit: 0.20
  BatchSize: 5000 #5000
  epoch: 500